version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:16
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev

volumes:
  mysql_data:
